name: Etiyalytics_sdk
description: A new Flutter package project.
version: 0.0.1


environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  json_annotation: ^4.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  logger: ^1.1.0
  build_runner: 
  freezed_annotation: ^2.1.0
  freezed: ^2.0.4
  json_serializable: ^6.3.1

flutter:
